SELECT [RuleId]
      ,[RelTermFieldId]
      ,[RunPeriodId]
      ,[QualityId]
      ,[ExactValue]
      ,[QualityLevel]
      ,[RuleDesc]
      ,[Status]
      ,[ActiveFlag]
      ,[InsertDate]
      ,[UpdatedDate]
      ,[UserName]
      ,[ResponsibleAnalystName]
FROM [TDUTIL].[DQ].[Rule]
